classwork/class16/blogr/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'

  resources :users do
    resources :posts
  end

end

classwork/class16/blogr/app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

classwork/class16/blogr/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
end

classwork/class16/blogr/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  
  protected

  def configure_permitted_parameters
    registration_params = [:email, :name, :phone, :password, :password_confirmation]
    devise_parameter_sanitizer.for(:sign_up) { 
        |u| u.permit(registration_params)
      }
    devise_parameter_sanitizer.for(:account_update) { 
        |u| u.permit(registration_params << :current_password)
      }
     
  end



end

classwork/class16/blogr/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = current_user.posts.new
  end

  def create
    @user = current_user
    @user.posts.create(safe_post_params)
    redirect_to user_posts_path(@user)
  end

  private

  def safe_post_params
    params.require(:post).permit(:title, :body)
  end
end

classwork/class16/blogr/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @user_count = User.all.count
    @users = User.all
  end

end

classwork/class16/blogr/app/views/posts/index.html.erb
<h2><%= @user.name %>'s posts!</h2>

<ul>
<% @posts.each do |post| %>
  <li><%= link_to post.title, user_post_path(@user, post) %></li>
<% end %>
</ul>

classwork/class16/blogr/app/views/posts/new.html.erb
<h1>New post by you, <%= current_user.name %></h1>

<div>
  <%= form_for [current_user, @post] do |f| %>
    <p>Title: <%= f.text_field :title %></p>
    <p>Body: <%= f.text_area :body %></p>
    <p><%= f.submit "Post!", class: "btn btn-primary btn-md" %></p>
  <% end %>
</div>

classwork/class16/blogr/app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<h3>by <%= link_to @post.user.name, user_posts_path(@post.user) %></h3>

<p><%= @post.body %></p>